import CONFIG from "@config/config";
import getArticle from "./getArticle";
import getCategoriesMenu from "./getCategoriesMenu";

const getLevel3Data = async (locale, category, url) => {
  const CMSConfigAPI = CONFIG.api.cms || "http://localhost:1337";

  const articleData = await getArticle(locale, category, url);

  if (articleData?.data?.length > 0) {
    articleData.data[0].attributes.article = true;
    const categoriesMenuData = await getCategoriesMenu(locale);

    return { data: articleData.data, categoriesMenuData };
  }

  const categoryParams = [
    `filters[slug_id][$eq]=docs&fields=name,url,slug_id,position&populate[category_docs][fields]=name,url,position&populate[category_docs][populate][article_docs][fields]=title,url,position&populate[category_docs][populate][level_2_docs][fields]=name,url,position&populate[category_docs][populate][level_2_docs][populate][article_docs][fields]=title,url,position&populate[category_docs][populate][level_2_docs][populate][level_3_docs][fields]=name,url,position&populate[category_docs][populate][level_2_docs][populate][level_3_docs][populate][article_docs][fields]=title,url,position,level_4_title&populate[category_docs][populate][level_2_docs][populate][level_3_docs][populate][level_4_docs][fields]=name,url,position&populate[category_docs][populate][level_2_docs][populate][level_3_docs][populate][level_4_docs][populate][article_docs][fields]=title,url,position${category === "docs" ? `&populate[category_docs][populate][level_2_docs][populate][level_3_docs][populate][icon]=*&populate[category_docs][populate][level_2_docs][populate][level_3_docs][populate][icon_small]=*&populate[category_docs][fields]=seo_title,seo_description,description&populate[category_docs][populate]=tags&populate[category_docs][populate][level_2_docs][fields]=seo_title,seo_description&populate[category_docs][populate][level_2_docs][populate][category_pic]=*&populate[category_docs][populate][level_2_docs][populate][article_docs][populate][icon]=*&populate[category_docs][populate][level_2_docs][populate][article_docs][fields]=level_4_title` : ""}`,
    `filters[slug_id][$eq]=desktop&fields=name,url,slug_id,position&populate[category_desktops][fields]=name,url,position&populate[category_desktops][populate][article_desktops][fields]=title,url,position&populate[category_desktops][populate][level_2_desktops][fields]=name,url,position&populate[category_desktops][populate][level_2_desktops][populate][article_desktops][fields]=title,url,position${category === "desktop" ? `&populate[category_desktops][fields]=seo_title,seo_description,description&populate[category_desktops][populate]=tags&populate[category_desktops][populate][level_2_desktops][fields]=seo_title,seo_description&populate[category_desktops][populate][level_2_desktops][populate][category_pic]=*&populate[category_desktops][populate][level_2_desktops][populate][article_desktops][populate][icon]=*&populate[category_desktops][populate][level_2_desktops][populate][article_desktops][fields]=level_4_title` : ""}`,
    `filters[slug_id][$eq]=docspace&fields=name,url,slug_id,position&populate[category_docspaces][fields]=name,url,position&populate[category_docspaces][populate][article_docspaces][fields]=title,url,position&populate[category_docspaces][populate][level_2_docspaces][fields]=name,url,position&populate[category_docspaces][populate][level_2_docspaces][populate][article_docspaces][fields]=title,url,position&populate[category_docspaces][populate][level_2_docspaces][populate][level_3_docspaces][fields]=name,url,position&populate[category_docspaces][populate][level_2_docspaces][populate][level_3_docspaces][populate][article_docspaces][fields]=title,url,position,level_4_title${category === "docspace" ? `&populate[category_docspaces][populate][level_2_docspaces][populate][level_3_docspaces][populate][icon]=*&populate[category_docspaces][populate][level_2_docspaces][populate][level_3_docspaces][populate][icon_small]=*&populate[category_docspaces][fields]=seo_title,seo_description,description&populate[category_docspaces][populate]=tags&populate[category_docspaces][populate][level_2_docspaces][fields]=seo_title,seo_description&populate[category_docspaces][populate][level_2_docspaces][populate][category_pic]=*&populate[category_docspaces][populate][level_2_docspaces][populate][article_docspaces][populate][icon]=*&populate[category_docspaces][populate][level_2_docspaces][populate][article_docspaces][fields]=level_4_title` : ""}`,
    `filters[slug_id][$eq]=mobile&fields=name,url,slug_id,position&populate[category_mobiles][fields]=name,url,position&populate[category_mobiles][populate][article_mobiles][fields]=title,url,position&populate[category_mobiles][populate][level_2_mobiles][fields]=name,url,position&populate[category_mobiles][populate][level_2_mobiles][populate][article_mobiles][fields]=title,url,position&populate[category_mobiles][populate][level_2_mobiles][populate][level_3_mobiles][fields]=name,url,position&populate[category_mobiles][populate][level_2_mobiles][populate][level_3_mobiles][populate][article_mobiles][fields]=title,url,position,level_4_title&populate[category_mobiles][populate][level_2_mobiles][populate][level_3_mobiles][populate][level_4_mobiles][fields]=name,url,position&populate[category_mobiles][populate][level_2_mobiles][populate][level_3_mobiles][populate][level_4_mobiles][populate][article_mobiles][fields]=title,url,position${category === "mobile" ? `&populate[category_mobiles][populate][level_2_mobiles][populate][level_3_mobiles][populate][icon]=*&populate[category_mobiles][populate][level_2_mobiles][populate][level_3_mobiles][populate][icon_small]=*&populate[category_mobiles][fields]=seo_title,seo_description,description&populate[category_mobiles][populate]=tags&populate[category_mobiles][populate][level_2_mobiles][fields]=seo_title,seo_description&populate[category_mobiles][populate][level_2_mobiles][populate][category_pic]=*&populate[category_mobiles][populate][level_2_mobiles][populate][article_mobiles][populate][icon]=*&populate[category_mobiles][populate][level_2_mobiles][populate][article_mobiles][fields]=level_4_title&populate[category_mobiles][populate][level_2_mobiles][populate][level_3_mobiles][populate][level_4_mobiles][fields]=position_top` : ""}`,
    `filters[slug_id][$eq]=workspace&fields=name,url,slug_id,position&populate[category_workspaces][fields]=name,url,position&populate[category_workspaces][populate][article_workspaces][fields]=title,url,position&populate[category_workspaces][populate][level_2_workspaces][fields]=name,url,position&populate[category_workspaces][populate][level_2_workspaces][populate][article_workspaces][fields]=title,url,position&populate[category_workspaces][populate][level_2_workspaces][populate][level_3_workspaces][fields]=name,url,position&populate[category_workspaces][populate][level_2_workspaces][populate][level_3_workspaces][populate][article_workspaces][fields]=title,url,position,level_4_title&populate[category_workspaces][populate][level_2_workspaces][populate][level_3_workspaces][populate][level_4_workspaces][fields]=name,url,position&populate[category_workspaces][populate][level_2_workspaces][populate][level_3_workspaces][populate][level_4_workspaces][populate][article_workspaces][fields]=title,url,position${category === "workspace" ? `&populate[category_workspaces][populate][level_2_workspaces][populate][level_3_workspaces][populate][icon]=*&populate[category_workspaces][populate][level_2_workspaces][populate][level_3_workspaces][populate][icon_small]=*&populate[category_workspaces][fields]=seo_title,seo_description,description&populate[category_workspaces][populate]=tags&populate[category_workspaces][populate][level_2_workspaces][fields]=seo_title,seo_description&populate[category_workspaces][populate][level_2_workspaces][populate][category_pic]=*&populate[category_workspaces][populate][level_2_workspaces][populate][article_workspaces][populate][icon]=*&populate[category_workspaces][populate][level_2_workspaces][populate][article_workspaces][fields]=level_4_title` : ""}`,
    `filters[slug_id][$eq]=integration&populate[articles][fields]=title,url`
  ];
  const categoryUrls = categoryParams.map(param => `${CMSConfigAPI}/api/categories/?&locale=${locale}&${param}`);
  const categoryFetchPromises = categoryUrls.map(url => fetch(url).then(res => res.json()));
  const categoryResults = await Promise.all(categoryFetchPromises);
  const categoryData = categoryResults.reduce((acc, result) => {
    if (result.data && Array.isArray(result.data)) {
      return acc.concat(result.data);
    }
    return acc;
  }, []);

  return { data: categoryData };
};

export default getLevel3Data;